# fly.toml app configuration file generated for game-server-brisk-skylark-1315 on 2026-05-30T14:58:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'game-server-brisk-skylark-1315'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
